# Generated by Django 6.0.1 on 2026-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='daily_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
